//go:build ignore

// gen_phantom.go — run via `go generate ./internal/phantom/`
// Regenerates the random pad array in phantom.go with cryptographically random bytes.
// Each call produces a new phantom.go, mutating the binary content and hash on every build.

package main

import (
	"crypto/rand"
	"fmt"
	"os"
	"strings"
	"time"
)

const outputFile = "phantom.go"

func main() {
	// Generate 256 random bytes
	pad := make([]byte, 256)
	if _, err := rand.Read(pad); err != nil {
		fmt.Fprintf(os.Stderr, "rand.Read: %v\n", err)
		os.Exit(1)
	}

	// Generate a UUID-like build ID
	uuid := make([]byte, 16)
	rand.Read(uuid)
	uuid[6] = (uuid[6] & 0x0f) | 0x40 // version 4
	uuid[8] = (uuid[8] & 0x3f) | 0x80 // variant bits
	buildID := fmt.Sprintf("%x-%x-%x-%x-%x",
		uuid[0:4], uuid[4:6], uuid[6:8], uuid[8:10], uuid[10:])

	// Format pad as hex byte literals
	var sb strings.Builder
	for i, b := range pad {
		if i%16 == 0 {
			sb.WriteString("\n\t")
		}
		fmt.Fprintf(&sb, "0x%02X, ", b)
	}
	padStr := strings.TrimSuffix(strings.TrimSpace(sb.String()), ",")

	content := fmt.Sprintf(`// AUTO-GENERATED by gen_phantom.go at %s — DO NOT EDIT
// Re-run: go generate ./internal/phantom/
package phantom

// BuildID is injected at compile time via -ldflags.
// Set by the build script, unique per build.
var BuildID = "dev-build"

// pad is a cryptographically random byte array regenerated on every go generate.
// It is never executed — its sole purpose is to mutate the binary hash between builds.
var pad = [256]byte{%s,
}
`,
		time.Now().UTC().Format(time.RFC3339),
		padStr,
	)
	_ = buildID // available for future use in content if needed

	if err := os.WriteFile(outputFile, []byte(content), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "WriteFile: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("[+] Regenerated %s with new random pad\n", outputFile)
}
